<?php

namespace Database\Seeders;

use App\Models\KategoriSublayanan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubLayananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sub = [
            [
                'skl_id' => 1,
                'kl_id' => 1,
                'skl_label' => 'Pemasangan Baru Perangkat Jaringan',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 2,
                'kl_id' => 1,
                'skl_label' => 'Pemindahan Lokasi Perangkat Jaringan dalam satu Unit Kerja',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 3,
                'kl_id' => 1,
                'skl_label' => 'Pemindahan Lokasi Perangkat Jaringan beda Unit Kerja',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 4,
                'kl_id' => 1,
                'skl_label' => 'Pelepasan Perangkat Jaringan',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 5,
                'kl_id' => 1,
                'skl_label' => 'Perubahan kecepatan internet/penambahan bandwidth unit kerja',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 6,
                'kl_id' => 2,
                'skl_label' => 'Perbaikan Perangkat Jaringan',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Internal',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 7,
                'kl_id' => 2,
                'skl_label' => 'Pengaduan Gangguan Jaringan Intra',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Internal',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 8,
                'kl_id' => 2,
                'skl_label' => 'Pemeliharaan Berkala Jaringan intra',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Internal',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 9,
                'kl_id' => 3,
                'skl_label' => 'Router',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 10,
                'kl_id' => 3,
                'skl_label' => 'Access Point',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 11,
                'kl_id' => 4,
                'skl_label' => 'Pembuatan VPS',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 12,
                'kl_id' => 4,
                'skl_label' => 'Perubahan VPS',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 13,
                'kl_id' => 4,
                'skl_label' => 'Penghapusan VPS',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 14,
                'kl_id' => 5,
                'skl_label' => 'Pencadangan Server',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Internal',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 15,
                'kl_id' => 5,
                'skl_label' => 'Pemulihan server',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Internal',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 16,
                'kl_id' => 5,
                'skl_label' => 'Pencadangan Data',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Internal',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 17,
                'kl_id' => 5,
                'skl_label' => 'Pemulihan Data',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Internal',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 18,
                'kl_id' => 6,
                'skl_label' => 'Pembuatan Akun',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Instansi Lain',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 19,
                'kl_id' => 6,
                'skl_label' => 'Perubahan Akun',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Instansi Lain',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 20,
                'kl_id' => 6,
                'skl_label' => 'Penghapusan Akun',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Instansi Lain',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 21,
                'kl_id' => 6,
                'skl_label' => 'Pemberian Akses Data',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Instansi Lain',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 22,
                'kl_id' => 7,
                'skl_label' => 'Verifikasi Pengadaan Perangkat TIK',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 23,
                'kl_id' => 7,
                'skl_label' => 'Verifikasi Penghapusan Perangkat TIK',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 24,
                'kl_id' => 8,
                'skl_label' => 'Pencatatan Aset Masuk',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Internal',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 25,
                'kl_id' => 8,
                'skl_label' => 'Pencatatan Aset Keluar',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Internal',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 26,
                'kl_id' => 9,
                'skl_label' => 'Pengusulan Layanan',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 27,
                'kl_id' => 9,
                'skl_label' => 'Penghapusan Layanan',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 28,
                'kl_id' => 9,
                'skl_label' => 'Perubahan Layanan',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 29,
                'kl_id' => 10,
                'skl_label' => 'Jaringan Intra',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 30,
                'kl_id' => 10,
                'skl_label' => 'Pusat Data',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 31,
                'kl_id' => 10,
                'skl_label' => 'Sistem Penghubung Layanan Pemerintah',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 32,
                'kl_id' => 10,
                'skl_label' => 'Aplikasi',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 33,
                'kl_id' => 10,
                'skl_label' => 'Rekomendasi Perangkat TIK',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 34,
                'kl_id' => 10,
                'skl_label' => 'Pos Elektronik',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 35,
                'kl_id' => 10,
                'skl_label' => 'Layanan Kepemerintahan',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 36,
                'kl_id' => 11,
                'skl_label' => 'Akun Zoom',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 37,
                'kl_id' => 11,
                'skl_label' => 'Perangkat Zoom',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 38,
                'kl_id' => 11,
                'skl_label' => 'Operator Zoom',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 39,
                'kl_id' => 11,
                'skl_label' => 'Ruangan Command Center',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 40,
                'kl_id' => 11,
                'skl_label' => 'Ruangan Rapat Lantai 1',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 41,
                'kl_id' => 11,
                'skl_label' => 'Ruangan Rapat Mini',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 42,
                'kl_id' => 12,
                'skl_label' => 'Pembuatan alamat pos elektronik',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 43,
                'kl_id' => 12,
                'skl_label' => 'Reset Password alamat pos elektronik',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 44,
                'kl_id' => 12,
                'skl_label' => 'Penambahan kuota mailbox',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 45,
                'kl_id' => 12,
                'skl_label' => 'Pengubahan alamat pos elektronik dan',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 46,
                'kl_id' => 12,
                'skl_label' => 'Penghapusan alamat pos elektronik.',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Individu ASN',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 47,
                'kl_id' => 13,
                'skl_label' => 'Operator',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Instansi Lain',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'skl_id' => 48,
                'kl_id' => 13,
                'skl_label' => 'Pengguna',
                'skl_status' => 1,
                'skl_role' => 'Super Admin, Unit Kerja, Instansi Lain',
                'created_by' => 1,
                'created_at' => now(),
            ]
        ];

        KategoriSublayanan::query()->insert($sub);
    }
}
